### ISSUE TITLE
14.8.1-ipsw script

### ISSUE THREAD

**Issue by TushckanchickBly** [itsnebulalol/14.8.1-ipsw#3]
I still can't figure it out, aa - what is this command in the script? Thanks
sudo aa extract -i ../payloadv2/fixup.manifest || true
sudo aa extract -i ../payloadv2/data_payload

**Comment by varette** [comment]
It's a tool for manipulating [Apple Archives](https://developer.apple.com/documentation/applearchive?language=objc), it was previously named `yaa`, so you might have to modify the script if you run an older version of MacOS.

**Comment by DrissiReda** [comment]
Is that available for linux devices?

**Comment by asdfugil** [comment]
Download [prebuilt IPSW](https://archive.org/download/14.8.1_ipsws)
